
# "cb" - shortened codebase
---
- hosts: control
  vars:
    project_ini_string: "project section=Settings file={{ settings_dir }}/{{ settings_file }}"
    saved_project: "{{ lookup('ini', project_ini_string) }}"
    operation: "{{ (op is defined) | ternary(op, 'none') }}"
    project: "{{ (cb is defined) | ternary(cb, saved_project) }}"
  gather_facts: no
  tasks:
    - name: default
      block:
        - name: "show error"
          debug:
            msg: "No operation specified."
      when: operation == "none"
    - name: boot
      block:
        - name: install python docker
          pip:
            virtualenv: "{{ playbook_dir }}/python"
            name:
              - docker-compose
        - name: populate docker-compose
          template:
            src: "{{ playbook_dir }}/env/docker-compose.j2"
            dest: "{{ playbook_dir }}/docker-compose.yml"
        - name: boot containers
          docker_compose:
            project_src: "{{ playbook_dir }}"
            state: present
      when: operation == "boot"
    - name: switch
      block:
        - name: populate settings file
          template:
            src: "{{ playbook_dir }}/env/base-docker.j2"
            dest: "{{ settings_dir }}/{{ settings_file }}"
      when: operation == "switch"
