---

- hosts: control
  vars:
    ansible_become: false
  gather_facts: false
  tasks:
    - name: install roles
      command: "ansible-galaxy install -r {{ playbook_dir }}/requirements.yml --roles-path {{ playbook_dir }}/roles"
...
