---

- hosts: control
  vars:
    ansible_become: false
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: install roles
      command: "ansible-galaxy install -r {{ playbook_dir }}/requirements.yml --roles-path {{ playbook_dir }}/roles"
...
