---
- hosts: "{{ variable_host | default('control') }}"
  gather_facts: no
  vars:
    arch_string: "{{ arch | default('') }}"
    use_arch: "{{ 'pi' if (arch_string | default('')) == 'pi' else '' }}"
    use_host: "{{ h | default('www.dev.org') }}"
    use_project: "{{ cb | default('my_project') }}"
    use_developer: "{{ dev | default(false) }}"

  tasks:        
    - name: create config directory
      file:
        path: "{{ settings_dir }}"
        state: directory
    - name: populate settings file
      template:
        src: "{{ playbook_dir }}/env/base-docker.j2"
        dest: "{{ settings_dir }}/{{ settings_file }}"
