

- block:

    - name: debug compose inputs
      ansible.builtin.debug:
        msg:
          compose_project_dir: "{{ compose_project_dir }}"
          app_compose_files: "{{ app_compose_files }}"
          app_compose_files_types: "{{ app_compose_files | map('type_debug') | list }}"
          env_file_path: "{{ env_file_path }}"
      delegate_to: localhost
      run_once: true

    - name: run tooling command via docker compose
      ansible.builtin.command: >-
        docker compose
        {{ app_compose_files | map('regex_replace', '^(.*)$', '-f \\1') | join(' ') }}
        --env-file {{ env_file_path }}
        --project-directory {{ compose_project_dir }}
        run --rm {{ tooling_service }}
        -lc {{ tooling_cmd | quote }}
      delegate_to: localhost
      run_once: true
      register: tooling_cmd_result

    - name: expose tooling result
      ansible.builtin.set_fact:
        tooling_output: "{{ tooling_cmd_result }}"      
  vars:
    compose_project_dir: "{{ playbook_dir }}"
    app_compose_files:
      - "{{ compose_project_dir }}/docker-compose.yml"
      - "{{ compose_project_dir }}/docker-compose.partial.yml"
    env_file_path: "{{ code_dir }}/{{ use_project }}/.env"
    tooling_service: tooling
    tooling_workdir: /var/www/project
    tooling_cmd: "composer install"
