
- name: create a unique temp file path
  ansible.builtin.tempfile:
    state: file
    suffix: "-{{ settings_file }}"
    path: /tmp
  register: settings_tmp

- name: populate settings file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/env/base-docker.j2"
    dest: "{{ settings_tmp.path }}"
    mode: "0600"

- name: retrieve file
  ansible.builtin.fetch:
    src: "{{ settings_tmp.path }}"
    dest: "{{ settings_dir }}/base-docker.ini"
    flat: true
    validate_checksum: false

- name: cleanup temp file
  ansible.builtin.file:
    path: "{{ settings_tmp.path }}"
    state: absent