
- block:

    - name:  ensure npm cache volume ownership
      ansible.builtin.include_tasks: "{{ playbook_dir }}/main_tooling_root.yml"
      vars:
        tooling_cmd: >-
          mkdir -p /tmp/npm-cache &&
          chown -R {{ ansible_user_uid }}:{{ ansible_user_gid }} /tmp/npm-cache


    - name: check for partial compose file
      ansible.builtin.stat:
        path: "{{ compose_project_dir }}/docker-compose.partial.yml"
      register: partial_compose
      run_once: true

    - name: run tooling command via docker compose
      ansible.builtin.command: >-
        docker compose
        -f {{ compose_project_dir }}/docker-compose.yml
        {% if partial_compose.stat.exists %}-f {{ compose_project_dir }}/docker-compose.partial.yml{% endif %}
        --env-file {{ env_file_path }}
        --project-directory {{ compose_project_dir }}
        run --rm {{ tooling_service }}
        -lc {{ tooling_cmd | quote }}
      run_once: true
      register: tooling_cmd_result

    - name: expose tooling result
      ansible.builtin.set_fact:
        tooling_output: "{{ tooling_cmd_result }}"      
  vars:
    compose_project_dir: "{{ compose_dir }}"
    env_file_path: "{{ lookup('env','HOME') }}/code/{{ use_project }}/.env"
    tooling_service: tooling
    tooling_cmd: "composer install"
