

- name: vhost.d dirs
  block:
    - name: ensure env dir exists (and is writable by vagrant)
      become: true
      ansible.builtin.file:
        path: "{{ compose_dir }}/env"
        state: directory
        owner: vagrant
        group: vagrant
        mode: "0775"
    - name: ensure env/vhost.d dir exists (and is writable by vagrant)
      become: true
      ansible.builtin.file:
        path: "{{ compose_dir }}/env/vhost.d"
        state: directory
        owner: vagrant
        group: vagrant
        mode: "0775"
  when: variable_host == 'node'


- name: set uid/gid for docker compose in .env
  ansible.builtin.lineinfile:
    path: "{{ code_dir }}/{{ use_project }}/.env"
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    create: true
  loop:
    - { key: "UID", value: "{{ ansible_user_uid }}" }
    - { key: "GID", value: "{{ ansible_user_gid }}" }
  delegate_to: localhost
  run_once: true
     

- name: check if env file exists
  ansible.builtin.stat:
    path: "{{ code_dir }}/{{ use_project }}/.env"
  register: env_file

- name: boot
  community.docker.docker_compose_v2:
    project_src: "{{ compose_dir }}"
    state: present
    remove_orphans: true
    env_files: "{{ env_file.stat.exists | ternary([code_dir ~ '/' ~ use_project ~ '/.env'], omit) }}"
    files: "{{ compose_files }}"
 
 