

- name: assert vhost.d directory exists
  ansible.builtin.file:
    path: "{{ compose_dir }}/env/vhost.d"
    state: directory
    mode: '0755'

- name: detect nginx config
  stat:
    path: "{{ compose_dir }}/env/vhost.d/{{ use_host }}_location"
  register: st
  
- name: copy file when using 'node'
  copy:
    src: "{{ playbook_dir }}/env/vhost.d/www.dev.org_location"
    dest: "{{ compose_dir }}/env/vhost.d/{{ use_host }}_location"
  when: use_host != 'www.dev.org' and not st.stat.exists
  

