
- name: configure
  shell: |
    docker exec -u www-data app php ./vendor/bin/empathy --set_docroot /var/www/project
    docker exec -u www-data app php ./vendor/bin/empathy --set_webroot {{ use_host }}
    docker exec -u www-data app php ./vendor/bin/empathy --set_publicdir ""
    docker exec -u www-data app php ./vendor/bin/empathy --misc tpl_cache
    docker exec -u www-data app php ./vendor/bin/empathy --set_dbserver db
    docker exec -u www-data app php ./vendor/bin/empathy --set_dbuser root
    docker exec -u www-data app php ./vendor/bin/empathy --set_dbpass example
    docker exec -u www-data app php ./vendor/bin/empathy --set_dbname project
    
