---


# ssh \
#   -i /home/vagrant/.ssh/vagrant_insecure_key \
#   -o StrictHostKeyChecking=no \
#   -o UserKnownHostsFile=/dev/null \
#   -o LogLevel=ERROR \
#   vagrant@node -C "ls"


- hosts: control
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    gh_owner: mikejw
    gh_repo: bdcli
    binary_name: bdcli_linux_amd64
    installed_binary_name: bdcli
    node_hosts:
      - www.dev.org
      - cms.dev.org
      - go.dev.org
      - node
  gather_facts: yes
  tasks:
    - name: virtualenv
      include_tasks: "{{ playbook_dir }}/vagrant_virtualenv.yml"
    - name: install pip packaging
      include_tasks: "{{ playbook_dir }}/vagrant_install_packaging.yml"
    - name: set hostname
      ansible.builtin.hostname:
        name: control
        use: systemd
    - name: install bdcli
      include_tasks: "{{ playbook_dir }}/vagrant_install_bdcli.yml"
    
    # 1) "control" line 
    - name: add control
      ansible.builtin.include_tasks: "{{ playbook_dir }}/vagrant_hosts_entry.yml"
      vars:
        ip: 127.0.0.1
        names:
          - control
          - localhost

    # 2) node machine line, IP derived from host "node"
    - name: add node host entry (dynamic IP)
      ansible.builtin.include_tasks: "{{ playbook_dir }}/vagrant_hosts_entry.yml"
      vars:
        target: node
        names:
          - node
   
- hosts: node
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
  gather_facts: yes
  roles:
    - geerlingguy.docker
  tasks:
    - name: Ensure unzip is installed (Debian/Ubuntu)
      apt:
        name: 
          - unzip
        state: present
        update_cache: yes
    - name: virtualenv
      include_tasks: "{{ playbook_dir }}/vagrant_virtualenv.yml"
    - name: install pip packaging
      include_tasks: "{{ playbook_dir }}/vagrant_install_packaging.yml"     
    - name: set hostname
      ansible.builtin.hostname:
        name: node
        use: systemd
    - name: "adding existing user {{ ansible_user }} to group docker"
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    - name: project(s) dir
      file:
        path: /home/vagrant/code
        state: directory
        owner: vagrant
        group: vagrant
    - name: working dir
      file:
        path: /home/vagrant/files
        state: directory
        owner: vagrant
        group: vagrant
    - name: install virtualenv
      ansible.builtin.apt:
        name: virtualenv
        state: present

    # 1) "node" line with dev aliases 
    - name: add node + dev aliases
      ansible.builtin.include_tasks: "{{ playbook_dir }}/vagrant_hosts_entry.yml"
      vars:
        ip: 127.0.0.1
        names:
          - node
          - www.dev.org
          - cms.dev.org
          - go.dev.org
          - localhost

    # 2) control machine line, IP derived from host "control"
    - name: add control host entry (dynamic IP)
      ansible.builtin.include_tasks: "{{ playbook_dir }}/vagrant_hosts_entry.yml"
      vars:
        target: control
        names:
          - control
          

...
