---

- hosts: control
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    gh_owner: mikejw
    gh_repo: bdcli
    binary_name: bdcli_linux_amd64
    installed_binary_name: bdcli
  gather_facts: false
  tasks:
    - name: virtualenv
      include_tasks: "{{ playbook_dir }}/vagrant_virtualenv.yml"
    - name: install pip packaging
      include_tasks: "{{ playbook_dir }}/vagrant_install_packaging.yml"
    - name: set hostname
      ansible.builtin.hostname:
        name: control
        use: systemd
    - name: install bdcli
      include_tasks: "{{ playbook_dir }}/vagrant_install_bdcli.yml"
   
- hosts: node
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
  gather_facts: yes
  roles:
    - geerlingguy.docker
  tasks:
    - name: virtualenv
      include_tasks: "{{ playbook_dir }}/vagrant_virtualenv.yml"
    - name: install pip packaging
      include_tasks: "{{ playbook_dir }}/vagrant_install_packaging.yml"     
    - name: set hostname
      ansible.builtin.hostname:
        name: node
        use: systemd
    - name: "adding existing user {{ ansible_user }} to group docker"
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    - name: project(s) dir
      file:
        path: /home/vagrant/code
        state: directory
        owner: vagrant
        group: vagrant
    - name: working dir
      file:
        path: /home/vagrant/files
        state: directory
        owner: vagrant
        group: vagrant
    - name: install virtualenv
      ansible.builtin.apt:
        name: virtualenv
        state: present
    - name: ensure www.dev.org points to node
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+localhost'
        line: "127.0.1.1\tlocalhost\twww.dev.org cms.dev.org go.dev.org"

...
