
---
- name: install virtualenv
  ansible.builtin.apt:
    name: virtualenv
    state: present
    update_cache: true
- name: clear folder
  ansible.builtin.file:
    path: ~/python
    state: absent
- name: setup virtualenv
  shell:
    cmd: virtualenv ~/python
  become: true
  become_user: vagrant
...
