
- hosts: control
  gather_facts: false
  vars:
    ansible_connection: local
  vars_files:
    - ~/.config/base-docker/settings.yml
  tasks:
    - name: template the hosts file
      template:
        src: "{{ playbook_dir}}/ansible/env/hosts.j2"
        dest: "{{ playbook_dir }}/ansible/hosts"
    - name: read encrypted values
      include_vars:
        file: "~/.config/base-docker/secrets.yml"
        name: secrets_vals    
    - name: create temp pem file
      copy: 
        content: "{{ secrets_vals.pem.proxy }}" 
        dest: /tmp/private.pem
        mode: '0600'
