
Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.box_version = "12.20250126.1"

    config.vm.network "public_network",
        ip: "10.0.0.33",
        netmask: "255.255.255.0"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision.yml"
        ansible.become = true
        ansible.extra_vars = {
          ansible_python_interpreter: "/usr/bin/python3"
        }
        ansible.compatibility_mode = "2.0"
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
end
